changing prep to match the new curriculum
LearnersGuild/playbook pull request #163
Opened 2017-08-01 15:13 UTC by bundacia

see [ch3684](https://app.clubhouse.io/learnersguild/story/3684/).

2017-08-01 16:07 UTC, tannerwelsh requested changes
Looking good, Trevor! I requested just a few additional modifications, otherwise I think this will be a good change. Might want to get @deadlyicon's eyes on this before a merge too.

2017-08-01 16:07 UTC, tannerwelsh commented on Runway/README.md
> + - Build a Random Quote Machine Incomplete
Let's get rid of these extra "Incomplete"s here

2017-08-01 16:07 UTC, tannerwelsh commented on Runway/README.md
> +projects:
Consider changing the above line to more strongly encourage continual learning:

> Done with all the required prep? Great! But don't stop there! Continuous learning is a core part of being a developer. Keep practicing by building these fundamental web development skills:

2017-08-01 16:07 UTC, tannerwelsh commented on Runway/README.md
>  - Get oriented to GitHub with [Hello World][gh-hello-guide], [Understanding the GitHub Flow][gh-flow-guide]
I think these GitHub exercises should be required

2017-08-01 16:07 UTC, tannerwelsh commented on Runway/README.md
>   - [Introduction](https://cos.learnersguild.org/)
I think one more indent space is needed for this to register as a sub list of "Read the following sections..."

2017-08-01 16:07 UTC, tannerwelsh commented on Runway/README.md
> +- Go through Codecademy's [Learn the Command Line][codecademy-cli] course
Let's change this language to "Complete Codecademy's..." (just a bit more explicit about the expectations)

2017-08-01 16:07 UTC, tannerwelsh commented on Runway/README.md
> +- Basic Algorithm Scripting (try to get through about half)
Let's not say just half. I think all of these are good exercises for folks to have experience with. We can always pare it down more later if it's too much.

2017-08-01 16:21 UTC, tannerwelsh commented
One other thing, what about having folks complete some kind of small project? My first thought is that we could port the old enrollment game challenge (https://gist.github.com/lg-bot/f306837bb0fd958ef5de) into a repo and update the instructions so that folks fork the repo and work on the steps. This way they're actually getting some exposure to a real workflow rather than working in contained, in-browser environments for everything.

2017-08-01 17:55 UTC, bundacia commented on Runway/README.md
> +- Basic Algorithm Scripting (try to get through about half)
works for me

2017-08-01 18:55 UTC, bundacia commented on Runway/README.md
> +- Go through Codecademy's [Learn the Command Line][codecademy-cli] course
👍

2017-08-01 18:56 UTC, bundacia commented on Runway/README.md
>   - [Introduction](https://cos.learnersguild.org/)
I think it's right how it is. This is how it renders for me:
<img width="876" alt="readme_md" src="https://user-images.githubusercontent.com/189699/28841854-8b265034-76c9-11e7-8d69-68148a7ed4ec.png">

2017-08-01 18:57 UTC, bundacia commented on Runway/README.md
> +projects:
👍

2017-08-01 18:57 UTC, bundacia commented on Runway/README.md
>  - Get oriented to GitHub with [Hello World][gh-hello-guide], [Understanding the GitHub Flow][gh-flow-guide]
ok

2017-08-01 19:05 UTC, bundacia commented
@tanner, that challenge is currently an in-browser activity as well, using js-bin, we could change that, but I'm hesitant to require too many things that are not in-browser. I don't want people to get stuck because they don't have access to a reliable computer they can install stuff on. I'd love for this prep to be able to be completed at a public library, for instance.

2017-08-01 19:05 UTC, bundacia commented on Runway/README.md
> + - Build a Random Quote Machine Incomplete
done

2017-08-01 20:01 UTC, tannerwelsh commented
@bundacia yeah that's a good point. That was a criteria of mine too, now that you mention it. I think it's a worthwhile standard for us to hold ourselves to. Ok, so in that case I think this all looks good 👍

2017-08-01 21:44 UTC, tannerwelsh approved these changes

2017-08-01 21:45 UTC, tannerwelsh commented
@deadlyicon assigning you to review since this should probs get the 👌 from you too

2017-08-02 00:20 UTC, jaredatron requested changes

2017-08-02 00:20 UTC, jaredatron commented on Runway/README.md
> +- Basic Algorithm Scripting (try to get through about half)
I'd remove `Object Oriented and Functional Programming` we don't really teach this anywhere explicitly anymore. I mostly recommend folks just do functional programming in JavaScript.

2017-08-02 00:20 UTC, jaredatron commented on Runway/README.md
>  - Get oriented to GitHub with [Hello World][gh-hello-guide], [Understanding the GitHub Flow][gh-flow-guide]
yes! Some very basic Git and GitHub skills should be required.

2017-08-02 00:20 UTC, jaredatron commented on Runway/README.md
> + - Build a Random Quote Machine Incomplete
you need to indent two spaces here

2017-08-02 00:20 UTC, jaredatron commented on Runway/README.md
>  ** Watch Karim Bishay's [presentation on Feedback](https://shereef.wistia.com/medias/8wx7n2fs65#)** (1 hour)
this line is not showing up as a bold line. I dont think you can have a space after the `**`

2017-08-02 00:21 UTC, jaredatron requested changes

2017-08-02 00:21 UTC, jaredatron commented on Runway/README.md
> + - Build a Random Quote Machine
i think you need two spaces to indent here

2017-08-02 13:06 UTC, tannerwelsh commented on Runway/README.md
> +- Basic Algorithm Scripting (try to get through about half)
@deadlyicon I think it's actually a good bit of prep, although the name is a little misleading. It just consists of exercises working with constructor functions, and then some basic "functional" array methods (sort, map, reduce). It's much more lowercase objects and functional programming than an introduction to the paradigms.

2017-08-02 14:01 UTC, merged

2017-08-03 15:41 UTC, tannerwelsh commented
Thx @bundacia!